name: Release Build

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: |
          mkdir build
          go build -v -ldflags="-s -w -H windowsgui -X cursor_history/internal/app.Version=${{ env.VERSION }}" -trimpath -o build/vscodehelper.exe

      - name: Create Installer
        run: |
          Start-Process -FilePath "./bin/innosetup-6.2.2.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait

      - name: Build Installer
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' setup.iss

      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID  }}
          key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET  }}
          region: oss-cn-hangzhou
          bucket: v8cloud
          assets: |
            installer/**:/cursor-history/
            
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            installer/CursorHistory_Setup_*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 